project:
  type: book
  output-dir: docs
  
book: 
  title: "Übung zur Vorlesung Statistik und Datenanalyse"
  author: "Christina Bogner"
  date: last-modified
  language: "de"
  chapters: 
    - index.qmd
    - part: "EINFÜHRUNG IN R"
      chapters: 
        - 01-erste-schritte.qmd
        - 02-rmarkdown.qmd
        - 03-ggplot.qmd
        - 04-einlesen.qmd
    - part: "EXPLORATIVE DATENANALYSE"
      chapters:
        - 05-explorative-qualitativ.qmd
        - 06-explorative-quantitativ.qmd
    - part: "STATISTISCHE MODELLIERUNG"
      chapters: 
        - 07-lineare-regression-ein-pred.qmd
    - part: "STATISTISCHE INFERENZ"
      chapters: 
        - 09-tests-infer.qmd
        - 10-konfidenzintervall-infer.qmd
    - part: "LABS: EIGENSTÄNDIGE ÜBUNGEN"
      chapters: 
        - 25-lab-01-intro-to-r.qmd
        - 30-lab-02-intro-to-data.qmd
        - 40-lab-03-linear-regression.qmd
    - references.qmd
  appendices:
    - 100-aufgabensammlung.qmd
  page-navigation: true
  downloads: [pdf, epub]
  sidebar:
    style: docked
    background: light

resources:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css
  
bibliography: ['statistik_und_datenanalyse.bib', '../../../Kurse/Literatur/IMS_book.bib', '../../../Kurse/Literatur/eoce.bib']

language: _language-de.yml

format:
  html:
    theme: cosmo
    code-copy: true
    css:
      - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css
      - stat_style.css  # your file

    df-print: paged
  pdf:
    documentclass: scrreport
    title: "Übung zur Vorlesung Statistik und Datenanalyse"
  epub:
    title: "Übung zur Vorlesung Statistik und Datenanalyse"


